export const race = {
  name: "II Desafío Medina Roja BTT",
  edition: "II Edición · 2026",
  date: "4 Julio 2026 · sábado",
  location: "Almedina · Ciudad Real",
  startPoint: "Parque Miguel Hernández",
  tagline: "Vuelve el desafío",
  heroImage: "/portada3-hero.jpg",
  modalities: {
    corta: { km: 30, ascent: 350, desc: "Terreno rojo, Camino de Aníbal y Fuente de la Zarza. 80 % pistas fluidas; apta para iniciados." },
    larga: { km: 50, ascent: 1000, desc: "Pistas rápidas, herradura y senderos técnicos en 50 km. El Camino de Aníbal al ecuador." },
  },
  startTime: "8:30 (8:00 si calor extremo)",
  price: "25 €",
  priceTiers: [
    { label: "Tramo 1", deadline: "hasta 29 mayo",     price: "25 €", note: "Maillot el día de la prueba" },
    { label: "Tramo 2", deadline: "30 mayo – 1 julio", price: "25 €", note: "Maillot después de la prueba" },
  ],
  registrationUrl: "https://deporchip.com/inscripciones/ii-desafio-medina-roja-mtb-almedina/",
  registrationOpen: true,
  // La carrera ya se celebró: los CTAs enlazan a la clasificación en lugar de a la
  // inscripción. Verificar que esta URL muestra los resultados (Deporchip suele
  // publicarlos en la misma ficha del evento).
  resultsUrl: "https://deporchip.com/inscripciones/ii-desafio-medina-roja-mtb-almedina/",
  reglamentoUrl: "/reglamento.pdf",
  autorizacionMenoresUrl: "/autorizacion-menores.pdf",
  schedule: [
    { time: "7:00",  title: "Recogida de dorsales", desc: "Parque Miguel Hernández, hasta las 8:15.", color: "oliva" },
    { time: "8:15",  title: "Briefing técnico",     desc: "Recorrido, avituallamiento, seguridad y material obligatorio.", color: "almagra" },
    { time: "8:30",  title: "Salida",               desc: "CORTA y LARGA juntas (8:00 si las condiciones meteo lo exigen).", color: "naranja" },
    { time: "13:00", title: "Cierre de meta",       desc: "Tiempo máximo 4:30 h. Comida y bebida al cruzar la línea.", color: "almagra" },
    { time: "13:30", title: "Entrega de trofeos",   desc: "3 primeros general, 1º local, 1ª femenina, 1º sub18 (máster por confirmar).", color: "mostaza" },
    { time: "14:00", title: "Comida popular",       desc: "Incluida en la inscripción. Plato manchego para inscritos y acompañantes.", color: "naranja" },
  ] as const,
  contact: {
    instagram: "https://www.instagram.com/desafiomedinarojabtt/",
    instagramHandle: "@desafiomedinarojabtt",
    facebook: "https://www.facebook.com/people/Desaf%C3%ADo-Medina-Roja/61577237314001/",
    facebookHandle: "Desafío Medina Roja",
    email: "medinarojabiketeam@gmail.com",
    phone: "por confirmar",
  },
  gpx: {
    corta: "/corta-30km.gpx",
    larga: "/larga-50km.gpx",
  },
  toteemiUrl: "https://toteemi.com/producto/inscripcion-desafio-medina-roja/",
  // Álbum completo de fotos en Google Drive (compartido "cualquiera con el enlace").
  // Se muestra en el botón "Ver todas las fotos" de la galería. Dejar "" lo oculta.
  driveAlbumUrl: "https://drive.google.com/drive/folders/1Dpm49VKu2sY2drJB23-zVjahIzM3xz8Q",
  // Selección curada que se incrusta en la web. `w`/`h` son las dimensiones reales
  // de cada foto (se capturan al optimizarlas) para respetar su orientación en el
  // lightbox. Vacío -> la galería solo muestra el botón a Drive.
  gallery: [
    { src: "/gallery/g01-9cce51f4.webp", alt: "Ambiente en la salida bajo los toldos de Almedina", w: 901, h: 1600 },
    { src: "/gallery/g02-c6a2f618.webp", alt: "El trazado con Almedina al fondo", w: 1200, h: 1600 },
    { src: "/gallery/g03-18a5ff42.webp", alt: "Sobre las pistas rojas del Campo de Montiel", w: 1200, h: 1600 },
    { src: "/gallery/g04-5542ca7f.webp", alt: "Grupo de corredores en el terreno rojo", w: 1200, h: 1600 },
    { src: "/gallery/g05-e4159143.webp", alt: "Rodando en pareja por el Campo de Montiel", w: 1200, h: 1600 },
    { src: "/gallery/g06-cc9be6da.webp", alt: "Corredor entre el rastrojo y los cerros", w: 1200, h: 1600 },
    { src: "/gallery/g07-944bfafc.webp", alt: "Trazando una curva entre las encinas", w: 1200, h: 1600 },
    { src: "/gallery/g08-11a2a445.webp", alt: "En plena competición por los senderos", w: 1200, h: 1600 },
    { src: "/gallery/g09-727e935c.webp", alt: "Bajada técnica por el terreno rojo", w: 1200, h: 1600 },
    { src: "/gallery/g10-14118f02.webp", alt: "Superando un tramo del recorrido", w: 1200, h: 1600 },
    { src: "/gallery/g11-d15904a4.webp", alt: "Corredor celebrando en pleno recorrido", w: 1200, h: 1600 },
    { src: "/gallery/g12-016d98c2.webp", alt: "Sonrisas en la línea de meta", w: 1600, h: 1200 },
    { src: "/gallery/g13-72dc9a11.webp", alt: "El arco de meta en el Parque Miguel Hernández", w: 860, h: 1600 },
    { src: "/gallery/g14-f65a3cf8.webp", alt: "Celebración en el podio", w: 1600, h: 999 },
    { src: "/gallery/g15-e564c5b2.webp", alt: "Levantando el trofeo", w: 1600, h: 1145 },
    { src: "/gallery/g16-3756499c.webp", alt: "Entrega de premios de la II edición", w: 1600, h: 1102 },
    { src: "/gallery/g17-417480e4.webp", alt: "Brindis tras cruzar la meta", w: 1600, h: 1048 },
    { src: "/gallery/g18-788165a5.webp", alt: "Los más pequeños, protagonistas del día", w: 1600, h: 1006 },
    { src: "/gallery/g19-d5979111.webp", alt: "El pueblo se vuelca con la prueba", w: 1200, h: 1600 },
    { src: "/gallery/g20-fbf179b7.webp", alt: "Familias en la entrega de premios", w: 1600, h: 896 },
  ] as { src: string; alt: string; w: number; h: number }[],
  sponsors: [
    { name: "Tienda Joseguí y Lola",     logo: "/sponsors/josegui-lola.webp",          url: null, hideName: true },
    { name: "Estanco Antonia",           logo: "/sponsors/estanco-antonia-v3.webp",    url: null, hideName: true },
    { name: "Ciclos Quijote",            logo: "/sponsors/ciclos-quijote.webp",        url: null, hideName: true },
    { name: "Pafgio",                    logo: "/sponsors/pafgio.webp",                url: "https://pafgiocycling.com/", hideName: true },
    { name: "Panadería Ortíz",           logo: "/sponsors/panaderia-ortiz.webp",       url: null, hideName: true },
    { name: "X-Sauce",                   logo: "/sponsors/x-sauce.webp",               url: "https://x-sauce.com/", hideName: true },
    { name: "Leña Selas",                logo: "/sponsors/lena-selas.webp",            url: null, hideName: true },
    { name: "Baúl Celia",                logo: "/sponsors/baul-celia.webp",            url: null, hideName: true },
    { name: "Casino",                    logo: "/sponsors/casino.webp",                url: null, hideName: true },
    { name: "Toteemi",                   logo: "/sponsors/toteemi.png",                url: null, hideName: true },
    { name: "Ayuntamiento de Almedina",  logo: "/sponsors/ayto-almedina.webp",         url: null },
    { name: "Graficas Matamoros",        logo: "/sponsors/graficas-matamoros.webp",    url: null, hideName: true },
    { name: "Be Fit Infantes",           logo: "/sponsors/befit-infantes.webp",        url: null, hideName: true },
    { name: "Diputación de Ciudad Real", logo: "/sponsors/diputacion-cr.webp",         url: null, hideName: true },
    { name: "JCCM · Somos Deporte",      logo: "/sponsors/clm-somos-deporte.webp",     url: null, hideName: true },
    { name: "Bodegas Tierras Rojas",     logo: "/sponsors/bodegas-tierras-rojas.webp", url: null, hideName: true },
    { name: "Cooperativa San Gregorio",  logo: "/sponsors/san-gregorio.webp",          url: null, hideName: true },
  ] as { name: string; logo: string | null; url: string | null; hideName?: boolean }[],
};
