export const race = {
  name: "II Desafío Medina Roja BTT",
  edition: "II Edición · 2026",
  date: "4 Julio 2026 · sábado",
  location: "Almedina · Ciudad Real",
  startPoint: "Parque Miguel Hernández",
  tagline: "Vuelve el desafío",
  heroImage: "/portada3-hero.jpg",
  modalities: {
    corta: { km: 30, ascent: 350, desc: "Terreno rojo, Camino de Aníbal y Fuente de la Zarza. 80 % pistas fluidas; apta para iniciados." },
    larga: { km: 50, ascent: 1000, desc: "Pistas rápidas, herradura y senderos técnicos en 50 km. El Camino de Aníbal al ecuador." },
  },
  startTime: "8:30 (8:00 si calor extremo)",
  price: "25 €",
  priceTiers: [
    { label: "Tramo 1", deadline: "hasta 29 mayo",     price: "25 €", note: "Maillot el día de la prueba" },
    { label: "Tramo 2", deadline: "30 mayo – 1 julio", price: "25 €", note: "Maillot después de la prueba" },
  ],
  registrationUrl: "https://deporchip.com/inscripciones/ii-desafio-medina-roja-mtb-almedina/",
  registrationOpen: true,
  reglamentoUrl: "/reglamento.pdf",
  autorizacionMenoresUrl: "/autorizacion-menores.pdf",
  schedule: [
    { time: "7:00",  title: "Recogida de dorsales", desc: "Parque Miguel Hernández, hasta las 8:15.", color: "oliva" },
    { time: "8:15",  title: "Briefing técnico",     desc: "Recorrido, avituallamiento, seguridad y material obligatorio.", color: "almagra" },
    { time: "8:30",  title: "Salida",               desc: "CORTA y LARGA juntas (8:00 si las condiciones meteo lo exigen).", color: "naranja" },
    { time: "13:00", title: "Cierre de meta",       desc: "Tiempo máximo 4:30 h. Comida y bebida al cruzar la línea.", color: "almagra" },
    { time: "13:30", title: "Entrega de trofeos",   desc: "3 primeros general, 1º local, 1ª femenina, 1º sub18 (máster por confirmar).", color: "mostaza" },
    { time: "14:00", title: "Comida popular",       desc: "Incluida en la inscripción. Plato manchego para inscritos y acompañantes.", color: "naranja" },
  ] as const,
  contact: {
    instagram: "https://www.instagram.com/desafiomedinarojabtt/",
    instagramHandle: "@desafiomedinarojabtt",
    facebook: "https://www.facebook.com/people/Desaf%C3%ADo-Medina-Roja/61577237314001/",
    facebookHandle: "Desafío Medina Roja",
    email: "medinarojabiketeam@gmail.com",
    phone: "por confirmar",
  },
  gpx: {
    corta: "/corta-30km.gpx",
    larga: "/larga-50km.gpx",
  },
  toteemiUrl: "https://toteemi.com/producto/inscripcion-desafio-medina-roja/",
  sponsors: [
    { name: "Tienda Joseguí y Lola",     logo: "/sponsors/josegui-lola.webp",          url: null, hideName: true },
    { name: "Estanco Antonia",           logo: "/sponsors/estanco-antonia-v3.webp",    url: null, hideName: true },
    { name: "Ciclos Quijote",            logo: "/sponsors/ciclos-quijote.webp",        url: null, hideName: true },
    { name: "Pafgio",                    logo: "/sponsors/pafgio.webp",                url: "https://pafgiocycling.com/", hideName: true },
    { name: "Panadería Ortíz",           logo: "/sponsors/panaderia-ortiz.webp",       url: null, hideName: true },
    { name: "X-Sauce",                   logo: "/sponsors/x-sauce.webp",               url: "https://x-sauce.com/", hideName: true },
    { name: "Leña Selas",                logo: "/sponsors/lena-selas.webp",            url: null, hideName: true },
    { name: "Baúl Celia",                logo: "/sponsors/baul-celia.webp",            url: null, hideName: true },
    { name: "Casino",                    logo: "/sponsors/casino.webp",                url: null, hideName: true },
    { name: "Toteemi",                   logo: "/sponsors/toteemi.png",                url: "https://toteemi.com/producto/inscripcion-desafio-medina-roja/", hideName: true },
    { name: "Ayuntamiento de Almedina",  logo: "/sponsors/ayto-almedina.webp",         url: null },
    { name: "Graficas Matamoros",        logo: "/sponsors/graficas-matamoros.webp",    url: null, hideName: true },
    { name: "Be Fit Infantes",           logo: "/sponsors/befit-infantes.webp",        url: null, hideName: true },
    { name: "Diputación de Ciudad Real", logo: "/sponsors/diputacion-cr.webp",         url: null, hideName: true },
    { name: "JCCM · Somos Deporte",      logo: "/sponsors/clm-somos-deporte.webp",     url: null, hideName: true },
    { name: "Bodegas Tierras Rojas",     logo: "/sponsors/bodegas-tierras-rojas.webp", url: null, hideName: true },
    { name: "Cooperativa San Gregorio",  logo: "/sponsors/san-gregorio.webp",          url: null, hideName: true },
  ] as { name: string; logo: string | null; url: string | null; hideName?: boolean }[],
};
